sudo: false

language: generic

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libc6-i386

before_install:
  - export PS4="$ "

before_script:
  - bin/install_fasmg
  - bin/fetch_ti84pce

script:
  - tests/test

notifications:
  irc:
    channels:
      - "irc.choopa.net#ez80-dev"
    on_success: change
    on_failure: always
    skip_join: true
